### ISSUE TITLE
Chechbox

### ISSUE THREAD

**Issue by geftimov** [XhinLiang/MDPreference#4]
Are you able to have animation for the checkbox prior Lollipop?

**Comment by XhinLiang** [comment]
The `CheckBox` of `material` has animation in everywhere **except** the `CheckBoxPreference`.
The `SwitchPreference` has the same problem, too.
I tried to fix it, but failed.
Can you give me some idea of this problem?

**Comment by geftimov** [comment]
Well I was making the same stuff in another project.
The CheckBoxPreference from com.android.support:preference-v7:23.2.1 was working but the whole view had different paddings.

I am talking about this class : http://developer.android.com/reference/android/support/v7/preference/CheckBoxPreference.html
It has the animations.
If I have the time I can make a pr with the changes.

**Comment by XhinLiang** [comment]
I have read the source code of `CheckBoxPreference` in `AOSP`.
But I can not fix this problem yet.
I am glad if you can help.
